name: bcnp-folia
version: '${version}'
main: org.altronmaxx.nerfphantomsfolia.Nerfphantoms_folia
api-version: 1.20
folia-supported: true
commands:
  nerfphantoms:
    usage: /cnp <help | toggle | kill | reload>
    permission-message: §7｜§6系統§7｜§f飯娘：§7你沒權限。
permissions:
  bcnp.*:
    description: Gives access to all NerfPhantoms commands
    default: op
    children:
      bcnp.all: true
  bcnp.all:
    description: Gives access to all NerfPhantoms commands
    children:
      bcnp.reload: true
      bcnp.kill: true
      bcnp.disablespawn.self: true
      bcnp.disablespawn.others: true
  bcnp.reload:
    description: Reload plugin config
    default: op
  bcnp.kill:
    description: Kill all phantoms in current world
    default: op
  bcnp.disablespawn.self:
    description: Command to disable phantom spawning for self
    default: op
  bcnp.disablespawn.others:
    description: Command to disable phantom spawning for other players
    default: op
  bcnp.disablespawn.auto:
    description: Phantom spawn disable active by default for player
    default: op